# escape=`

FROM microsoft/dotnet:1.1.1-sdk-nanoserver

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

WORKDIR \MusicStore
ADD samples samples
ADD NuGet.config .
ADD build build

RUN dotnet restore .\samples\MusicStore
RUN dotnet build .\samples\MusicStore

EXPOSE 5000
ENV ASPNETCORE_URLS http://0.0.0.0:5000
CMD dotnet run -p .\samples\MusicStore